# Generated by Django 3.2 on 2021-05-13 23:41

from django.db import migrations, models
import django.db.models.deletion
import groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('group_code', models.IntegerField(default=groups.models.code_generator, unique=True)),
                ('group_owner', models.CharField(default='manager', max_length=255)),
                ('member_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=groups.models.user_full_name, max_length=255)),
                ('email', models.CharField(default=groups.models.user_email, max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default=groups.models.user_full_name, max_length=255)),
                ('teacher_email', models.CharField(default=groups.models.user_email, max_length=255)),
                ('exam_perm', models.BooleanField(default=False)),
                ('group_owner', models.ManyToManyField(to='groups.Manager')),
                ('groups', models.ManyToManyField(to='groups.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default=groups.models.user_full_name, max_length=255)),
                ('student_email', models.CharField(default=groups.models.user_email, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('group_owner', models.ForeignKey(default='owner', on_delete=django.db.models.deletion.CASCADE, to='groups.manager')),
            ],
        ),
    ]
