# Generated by Django 3.2 on 2021-05-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, unique=True)),
                ('exam_id', models.IntegerField(default=1, unique=True)),
                ('date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
