# Generated by Django 3.2 on 2021-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_examsettings_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='disp_duration',
            field=models.CharField(choices=[(1800, '30 Minutes'), (3600, '1 Hour'), (5400, '1 Hr 30 Mins'), (7200, '2 Hours'), (9000, '2 Hrs 30 Mins'), (10800, '3 Hours')], default=1800, max_length=20),
            preserve_default=False,
        ),
    ]
