# Generated by Django 3.2 on 2021-05-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examsettings_disp_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='disp_duration',
            field=models.IntegerField(choices=[(1800, '30 Minutes'), (3600, '1 Hour'), (5400, '1 Hr 30 Mins'), (7200, '2 Hours'), (9000, '2 Hrs 30 Mins'), (10800, '3 Hours')]),
        ),
    ]
