# Generated by Django 3.2 on 2021-05-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_examsettings_disp_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='duration',
            field=models.DurationField(default=1800),
        ),
    ]
