# Generated by Django 3.2 on 2021-05-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_examsettings_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='duration',
            field=models.DurationField(default=1),
        ),
        migrations.AlterField(
            model_name='examsettings',
            name='exam_id',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
