# Generated by Django 3.2 on 2021-05-14 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_examsettings_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
