# Generated by Django 3.2 on 2021-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_alter_examsettings_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsettings',
            name='group',
            field=models.CharField(default='group', max_length=50),
        ),
    ]
