# Generated by Django 3.2 on 2021-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_examsettings_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsettings',
            name='exam_id',
        ),
    ]
