# Generated by Django 3.2 on 2021-05-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_auto_20210515_0148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='ExamSetting',
        ),
    ]
