# Generated by Django 3.2 on 2021-05-15 22:33

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_rename_exam_examsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_choices', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4')], max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examquestion')),
            ],
        ),
        migrations.AddField(
            model_name='examsetting',
            name='no_of_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examsetting',
            name='disp_duration',
            field=models.IntegerField(choices=[(30, '30 Minutes'), (60, '1 Hour'), (90, '1 Hr 30 Mins'), (120, '2 Hours'), (150, '2 Hrs 30 Mins'), (180, '3 Hours')]),
        ),
        migrations.DeleteModel(
            name='ExamQuestions',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examsetting'),
        ),
    ]
