# Generated by Django 3.2 on 2021-05-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0022_auto_20210516_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionschoice',
            name='question_choices',
        ),
        migrations.AddField(
            model_name='questionschoice',
            name='choice1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionschoice',
            name='choice2',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionschoice',
            name='choice3',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionschoice',
            name='choice4',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
