# Generated by Django 3.2 on 2021-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0023_auto_20210516_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamSetting',
            new_name='Exam',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='choice1',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='choice2',
            field=models.CharField(default=2, max_length=50),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='choice3',
            field=models.CharField(default=3, max_length=50),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='choice4',
            field=models.CharField(default=4, max_length=50),
        ),
        migrations.DeleteModel(
            name='QuestionsChoice',
        ),
    ]
