# Generated by Django 3.2 on 2021-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_auto_20210516_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='iterable',
            field=models.IntegerField(default=0),
        ),
    ]
