# Generated by Django 3.2 on 2021-05-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0026_exam_iterable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='iterable',
        ),
    ]
