# Generated by Django 3.2 on 2021-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_remove_exam_iterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_model',
            field=models.BooleanField(default=False),
        ),
    ]
