# Generated by Django 3.2 on 2021-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_exam_question_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='question_model',
            new_name='exam_model',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='model',
            field=models.IntegerField(default=1),
        ),
    ]
