# Generated by Django 3.2 on 2021-07-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_alter_examquestion_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamQuestion',
            new_name='ExamMCQ',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='no_of_questions',
            new_name='mcq_questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='true_false_questions',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=5)),
                ('model', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
