# Generated by Django 3.2 on 2021-07-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_auto_20210707_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='true_false_questions',
            new_name='tf_questions',
        ),
    ]
