# Generated by Django 3.2 on 2021-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0032_rename_true_false_questions_exam_tf_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammcq',
            name='correct_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examtf',
            name='correct_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
