# Generated by Django 3.2 on 2021-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0037_auto_20210707_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='no_of_questions',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
