# Generated by Django 3.2 on 2021-07-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0041_alter_mcqanswersheet_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqanswersheet',
            name='question_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.exammcq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tfanswersheet',
            name='question_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exams.examtf'),
            preserve_default=False,
        ),
    ]
