# Generated by Django 3.2 on 2021-07-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_auto_20210710_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqanswersheet',
            name='question_title',
        ),
        migrations.AlterField(
            model_name='mcqanswersheet',
            name='answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
    ]
